// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_TIuZawyilMdr6CuVRDTF2x8a3C2zl0',
    appId: '1:132647767583:web:c6fc4151b6d1b02929cf2a',
    messagingSenderId: '132647767583',
    projectId: 'smc-erp-ce860',
    authDomain: 'smc-erp-ce860.firebaseapp.com',
    storageBucket: 'smc-erp-ce860.appspot.com',
    measurementId: 'G-6SKLLMMDL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEfW9317ghQXD2SizwI5DoC1lRhOlkVs',
    appId: '1:132647767583:android:628d34de213a409a29cf2a',
    messagingSenderId: '132647767583',
    projectId: 'smc-erp-ce860',
    storageBucket: 'smc-erp-ce860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFIvzKnG_e9Jp71m-ElOxZBcede1mRrw',
    appId: '1:132647767583:ios:8c6ef21ea571fa1829cf2a',
    messagingSenderId: '132647767583',
    projectId: 'smc-erp-ce860',
    storageBucket: 'smc-erp-ce860.appspot.com',
    iosBundleId: 'com.example.smlcErp',
  );
}
